export const SET_SCHEMA_FORM_DATA = "SET_SCHEMA_FORM_DATA";
export const SET_SCHEMA_FORM_DATA_VALID = "SET_SCHEMA_FORM_DATA_VALID";
export const CREATE_SCHEMA_FORM_STORE = "CREATE_SCHEMA_FORM_STORE";
export const REMOVE_SCHEMA_FORM_STORE = "REMOVE_SCHEMA_FORM_STORE";
